# Generated by Django 5.0.2 on 2024-02-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='level',
            field=models.CharField(choices=[('Ing', 'Inngenieria'), ('TSU', 'Tecnico Superior Universitario'), ('Ma', 'Maestria')], max_length=10, verbose_name='Nivel'),
        ),
    ]
