# Generated by Django 5.0.2 on 2024-02-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_career_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name': 'carrera'},
        ),
    ]
